set -e
true
true
/home/sandra/miniconda3/envs/ngs/bin/spades-core /media/sf_METAG/unit_3/ECTV_isolate/K21/configs/config.info /media/sf_METAG/unit_3/ECTV_isolate/K21/configs/isolate_mode.info
/home/sandra/miniconda3/envs/ngs/bin/spades-core /media/sf_METAG/unit_3/ECTV_isolate/K33/configs/config.info /media/sf_METAG/unit_3/ECTV_isolate/K33/configs/isolate_mode.info
/home/sandra/miniconda3/envs/ngs/bin/spades-core /media/sf_METAG/unit_3/ECTV_isolate/K55/configs/config.info /media/sf_METAG/unit_3/ECTV_isolate/K55/configs/isolate_mode.info
/home/sandra/miniconda3/envs/ngs/bin/python3 /home/sandra/miniconda3/envs/ngs/share/spades/spades_pipeline/scripts/copy_files.py /media/sf_METAG/unit_3/ECTV_isolate/K55/before_rr.fasta /media/sf_METAG/unit_3/ECTV_isolate/before_rr.fasta /media/sf_METAG/unit_3/ECTV_isolate/K55/assembly_graph_after_simplification.gfa /media/sf_METAG/unit_3/ECTV_isolate/assembly_graph_after_simplification.gfa /media/sf_METAG/unit_3/ECTV_isolate/K55/final_contigs.fasta /media/sf_METAG/unit_3/ECTV_isolate/contigs.fasta /media/sf_METAG/unit_3/ECTV_isolate/K55/first_pe_contigs.fasta /media/sf_METAG/unit_3/ECTV_isolate/first_pe_contigs.fasta /media/sf_METAG/unit_3/ECTV_isolate/K55/strain_graph.gfa /media/sf_METAG/unit_3/ECTV_isolate/strain_graph.gfa /media/sf_METAG/unit_3/ECTV_isolate/K55/scaffolds.fasta /media/sf_METAG/unit_3/ECTV_isolate/scaffolds.fasta /media/sf_METAG/unit_3/ECTV_isolate/K55/scaffolds.paths /media/sf_METAG/unit_3/ECTV_isolate/scaffolds.paths /media/sf_METAG/unit_3/ECTV_isolate/K55/assembly_graph_with_scaffolds.gfa /media/sf_METAG/unit_3/ECTV_isolate/assembly_graph_with_scaffolds.gfa /media/sf_METAG/unit_3/ECTV_isolate/K55/assembly_graph.fastg /media/sf_METAG/unit_3/ECTV_isolate/assembly_graph.fastg /media/sf_METAG/unit_3/ECTV_isolate/K55/final_contigs.paths /media/sf_METAG/unit_3/ECTV_isolate/contigs.paths
true
/home/sandra/miniconda3/envs/ngs/bin/python3 /home/sandra/miniconda3/envs/ngs/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /media/sf_METAG/unit_3/ECTV_isolate/scaffolds.fasta --misc_dir /media/sf_METAG/unit_3/ECTV_isolate/misc --threshold_for_breaking_scaffolds 3
true
